"""update city

Revision ID: 249806f44eee
Revises: b0d6514a6971
Create Date: 2021-09-01 08:51:57.177357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249806f44eee'
down_revision = 'b0d6514a6971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_country_id_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_country_id_fkey', 'city', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
